all: wordgen wordsearch pager launcher

wordgen: wordgen.c
	gcc -o wordgen wordgen.c

wordsearch: wordsearch.c
	gcc -o wordsearch wordsearch.c

pager: pager.c
	gcc -o pager pager.c

launcher: launcher.c
	gcc -o launcher launcher.c

